
object Versions {
    const val coreKtx = "1.8.0"
    const val appCompat = "1.6.1"
    const val constraint = "2.1.4"
    const val material = "1.8.0"
    const val junit = "4.13.2"
    const val testExt = "1.1.5"
    const val espresso = "3.5.1"
    const val navigation = "2.5.2"
    const val retrofit = "2.9.0"
    const val moshi = "1.14.0"
    const val ok_http = "4.10.0"
    const val hilt = "2.44"
    const val hiltCompiler = "2.44"
    const val logger = "2.2.0"
    const val glide = "4.15.0"
    const val swipeRefresh = "1.1.0"
    const val coil = "1.4.0"
    const val runtime = "2.5.1"
    const val extensions = "2.2.0"
    const val viewModel = "2.5.1"
    const val livedata = "2.5.1"
    const val coroutines = "1.6.4"
    const val coroutinesCore = "1.3.9"
    const val gson = "2.10.1"
    const val dataStore = "1.0.0-alpha01"
}